woowa-camp-2023-4/backend

src/main/java/com/woowa/woowakit/domain/order/domain/Order.java, src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java, src/main/java/com/woowa/woowakit/domain/order/domain/OrderStatus.java, src/main/java/com/woowa/woowakit/domain/order/domain/Payment.java, src/main/java/com/woowa/woowakit/domain/order/domain/TotalPrice.java, src/main/java/com/woowa/woowakit/domain/order/domain/converter/TotalPriceConverter.java, src/main/resources/schema.sql
주문 , 결제를 위한 기반 다지기
- Order
- Payment
- OrderItem
=> feat: Order Entity 생성

src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java, src/main/java/com/woowa/woowakit/domain/order/domain/Order.java, src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java, src/main/java/com/woowa/woowakit/global/config/PayConfig.java, src/test/java/com/woowa/woowakit/domain/order/domain/validator/OrderValidatorImplTest.java, src/test/java/com/woowa/woowakit/domain/order/fixture/OrderFixture.java, src/test/java/integration/helper/MemberHelper.java, src/test/java/integration/helper/OrderHelper.java, src/test/java/integration/helper/ProductHelper.java, src/test/java/integration/order/OrderIntegrationTest.java
#13  - 연관 issue
#42  - 해당 pr 추가 진행
가주문
`POST /orders/pre`
주문
`POST /orders`
주문은 재고확보와 결제를 포함합니다
현재 로직 중 product 양, 재고에 비관적 락을 통해 구현했습니다
향후 성능 이슈가 발생할 수 있으며 이슈레이징하겠습니다
추가 고도화 시 성능 개선이 필요합니다
각 도메인 하위에 fixture폴더를 추가해주세요!
```java
order/fixture
public static OrderItemBuilder anOrderItem() {
return OrderItem.builder()
.image(Image.from("image"))
.name("name")
.price(Money.from(1000L))
.productId(1L)
.quantity(Quantity.from(1L));
}
public static OrderBuilder anOrder() {
return Order.builder()
.memberId(1L)
.orderItems(List.of(anOrderItem().build(),
anOrderItem()
.productId(2L)
.name("해산물 밀키트")
.price(Money.from(2000L)).build()));
}
```
```java
@MockBean
private PaymentService paymentService;
```
위 방식으로 처리했습니다 편리해서 공유합니다
현재 given이 너무 길어지는 문제가 있으며 중복 코드가 발생하고 있습니다
Product를 등록하고 올려놓는다. 라는 전제조건을 하나로 …
=> test: 주문 controller추가, 주문 관련 단위테스트, 통합테스트 추가

src/main/resources/logback-variables.properties
로깅 저장 위치 변경
```
LOG_DIR=~/spring/logs
```
=> 로깅 저장 위치 변경

src/main/java/com/woowa/woowakit/domain/auth/application/AuthService.java, src/main/java/com/woowa/woowakit/domain/auth/dto/response/LoginResponse.java, src/main/java/com/woowa/woowakit/domain/order/dto/response/OrderDetailResponse.java, src/main/resources/application-local.yml, src/test/java/integration/member/MemberIntegrationTest.java
- 사용자 정보를 로그인 시 함꼐 반환
- order 조회 시 uuid 반환
커밋 로그 확인
=> feat: 프론트엔드에 맞추기 위해 응답 DTO 수정

src/main/java/com/woowa/woowakit/domain/product/domain/product/converter/ProductImageConverter.java, src/main/resources/application.yml, src/test/java/integration/product/ProductIntegrationTest.java
=> feat: 이미지 저장을 위해 최대 크기 5MB로 확장 및 컨버터 로직 제거

src/main/java/com/woowa/woowakit/domain/auth/domain/Member.java, src/main/java/com/woowa/woowakit/domain/cart/domain/CartItem.java, src/main/java/com/woowa/woowakit/domain/payment/domain/Payment.java, src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentHandler.java, src/main/java/com/woowa/woowakit/domain/product/domain/product/Product.java, src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stock.java, src/main/java/com/woowa/woowakit/global/config/WebClientConfig.java, src/main/resources/schema.sql
- 데이터베이스 테이블 대문자 -> 소문자로 변경
- WebClient 로깅
- paymentHandler 기눙 네이밍 변경
=> 데이터베이스 테이블 대문자 -> 소문자로 변경

src/main/java/com/woowa/woowakit/global/config/WebClientConfig.java, src/main/resources/application.yml
webClient 타임아웃 시간 1초 -> 3초으로 늘렸습니다.
webClient 타임아웃 시간 1초 -> 3초
=> webClient 타임아웃 시간 1초 -> 3초

src/main/java/com/woowa/woowakit/domain/product/application/StockProcessingService.java, src/main/java/com/woowa/woowakit/global/error/CommonExceptionHandler.java, src/main/resources/application-prod.yml
=> fix: prod.yml 및 오류 해결

build.gradle, src/main/resources/application-local.yml, src/main/resources/application.yml
관련 이슈 : #18 
현재 모든 메트릭을 열어놓았기 때문에 보안적 문제가 있습니다
actuator 포트와 base url을 환경변수로 빼내어 관리함으로써 어느정도의 보안적 문제를 완화한 상태입니다
=> feat: 메트릭 모니터링 설정 추가

.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml, src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
=> feat: deploy 환경 변수 추가, 로그 보강

src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java, src/main/java/com/woowa/woowakit/domain/order/domain/Order.java, src/main/java/com/woowa/woowakit/domain/order/domain/handler/CartItemDeletionEventHandler.java, src/main/java/com/woowa/woowakit/domain/order/domain/handler/ProductQuantityEventHandler.java, src/main/java/com/woowa/woowakit/global/interceptor/AuthenticationInterceptor.java
=> fix: order, auth 로그 보강

src/main/java/com/woowa/woowakit/domain/cart/api/CartItemController.java, src/main/java/com/woowa/woowakit/domain/cart/application/CartItemService.java, src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java, src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java, src/main/java/com/woowa/woowakit/domain/product/application/StockService.java
=> fix: CartItem, Product, Stock 로깅 추가

src/main/java/com/woowa/woowakit/global/error/CommonExceptionHandler.java
특정 요청 시 두 번의 짧은 동일한 생성 요청이 들어왔을 경우 unique key 에러가 발생할 수 있음
이를 핸들링하여 coflict를 내려주는 정책을 세팅함
=> feat: unique key 에러 추가

src/main/java/com/woowa/woowakit/domain/product/api/StockSchedulerController.java
=> StockScheduler 임시 앤드포인트 추가

.github/workflows/dev-deploy.yml, src/main/java/com/woowa/woowakit/infra/aws/s3/S3ImageUploader.java, src/main/java/com/woowa/woowakit/infra/aws/s3/S3Uploader.java
#100 에 명시한 문제 해결
이미지 파일 이름을 UUID로 생성하여 업로드하도록 변경
=> fix: 이름이 같으면 기존 이미지가 새 이미지에 덮어쓰기 되는 문제 해결

src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java, src/main/java/com/woowa/woowakit/domain/order/domain/Order.java, src/main/java/com/woowa/woowakit/domain/payment/domain/PaySaveService.java, src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentHandler.java, src/main/java/com/woowa/woowakit/global/config/ImageUploadConfig.java, src/main/java/com/woowa/woowakit/global/config/MetricConfig.java, src/main/java/com/woowa/woowakit/global/config/PayConfig.java
주문 결제 성공에 따른 비즈니스 메트릭을 추가했습니다
취소 처리에 따라 비즈니스 메트릭을 추가해야합니다
=> feat: 비즈니스 메트릭 추가 (주문, 결제)

build.gradle, src/test/java/com/woowa/woowakit/restDocsHelper/RestDocsHelper.java
누락된 스니펫을 보강하고 bootJar 시 자동으로 파일을 생성하도록 변경했습니다.
=> spring-rest-docs 오류 수정

src/docs/asciidoc/apis.adoc, src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java, src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java, src/main/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryCustom.java, src/main/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryCustomImpl.java, src/main/java/com/woowa/woowakit/domain/order/domain/OrderRepository.java, src/main/java/com/woowa/woowakit/domain/order/dto/request/OrderSearchRequest.java, src/test/java/com/woowa/woowakit/domain/order/api/OrderControllerTest.java, src/test/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryTest.java
안녕하세요 화나는 화요일입니다.
저희 oom 이슈의 원인으로 파악되는 주문 목록 조회에 커서를 적용했습니다.
커밋 로그 봐주세요
기존 테스트 재활용 + RestDocs 부분만 바꿨습니다.
=> feat: 주문 목록 조회 커서 적용 (#116)

src/main/java/com/woowa/woowakit/domain/cart/api/CartItemController.java, src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
=> refactor: 로그 보강 

.github/workflows/dev-deploy.yml, src/main/java/com/woowa/woowakit/domain/order/domain/mapper/OrderMapper.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/java/com/woowa/woowakit/domain/order/domain/mapper/OrderMapperTest.java
스레드풀 - 스트레스 테스트 시 cpu 자원이 남아 200으로 복귀
cors - 승윤님이 포함시켜달라고 함
예외 - 스트레스 테스트 시 버그 발견
=> fix: 잘못된 상품 id로 주문할 경우 예외 반환, cors 설정, 스레드풀 200으로 복귀

src/main/java/com/woowa/woowakit/global/error/UnAuthorizationException.java, src/main/java/com/woowa/woowakit/global/interceptor/UserAuthorityInterceptor.java
`권한이 없습니다 ->  로그인이 필요합니다` 로 변경했습니다.
=> 로그인이 필요한 요청에 메시지 변경

src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
=> feat: 캐시 타는지 로그 추가

src/main/java/com/woowa/woowakit/domain/order/domain/mapper/OrderMapper.java, src/main/java/com/woowa/woowakit/domain/order/exception/QuantityNotEnoughException.java, src/test/java/integration/order/OrderIntegrationTest.java, src/test/resources/application.yml
상품 재고가 부족한 경우 "상품의 재고가 부족합니다" 에러 메시지를 응답하도록 변경
=> 상품 재고가 부족한 경우 "상품의 재고가 부족합니다" 에러 메시지를 응답하도록 변경
